version: '3.2'

services:
  server:
    build: .
    image: miner-proxy:latest
    ports:
      - 9999:9999
    command: miner-proxy -l :9999 -r asia2.ethermine.org:5555 -k 12345

  client:
    build: .
    image: miner-proxy:latest
    ports:
      - 9999:9999
    command: miner-proxy -l :9999 -r 1.1.1.1:9999 -k 12345 -c