on:
  push: # 每次 push 的时候触发

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: chmod +x ./build.sh &&./build.sh
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: |
            ./miner-proxy_windows_amd64.exe
            ./miner-proxy_windows_arm.exe
            ./miner-proxy_darwin_amd64
          args: -fq
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            miner-proxy_darwin_amd64
            miner-proxy_linux_amd64
            miner-proxy_linux_arm
            miner-proxy_windows_amd64.exe
            miner-proxy_windows_arm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}